name: Docker Build and Push

# Activar este flujo de trabajo en cada push a la rama principal
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código fuente
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    # 2. Configurar Docker Buildx
    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Iniciar sesión en Docker Hub
    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Construir y subir la imagen de Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./                # Contexto donde se encuentra el Dockerfile
        file: ./Dockerfile         # Ruta al archivo Dockerfile en la raíz del proyecto
        push: true
        tags: yohandry10/first-r:latest  # Cambia a tu nombre de usuario y repositorio de Docker Hub

    # 5. Verificar la imagen Docker construida
    - name: Verify Docker Image
      run: |
        docker run -d -p 80:80 yohandry10/first-r:latest
        docker ps -a
